name: vku_expense_ocr
description: "VKU Receipt OCR & Expense Tracker — Mini-Project 3 (Mobile Cross-Platform Development)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^13.2.0

  # Hardware & OCR
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7

  # Local Persistence
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2

  # Utilities & Formatting
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_receipts/
    - assets/images/
